name: MERN CD

on:
  workflow_dispatch:  # Manual trigger for testing
  push: 
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # Only run if secrets exist
    if: ${{ env.EC2_HOST != '' }}
    env:
      EC2_HOST: ${{ secrets.EC2_HOST }}

    steps:
      # First check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Then deploy via SSH
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |-
            cd devops-mern-todo/ 
            git pull origin main
            docker-compose down
            docker-compose up --build -d