name: MERN CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")' || mongo --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Wait for MongoDB to be ready
        run: |
          echo "Waiting for MongoDB on localhost:27017..."
          for i in {1..30}; do
            if nc -z localhost 27017; then
              echo "MongoDB is ready"; break
            fi
            sleep 2
          done

      # no extra mongosh install: use TCP wait and npm seeding

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Seed MongoDB
        working-directory: backend
        env:
          MONGO_URI: mongodb://localhost:27017/expense-tracker
        run: node seedTasksData.js

      - name: Run backend tests
        working-directory: backend
        env:
          MONGO_URI: mongodb://localhost:27017/expense-tracker
        run: npm test
